# ===========================================================================================================================================#
# SUBMITTER

# Specify if CMILib is installed in your server.
enable_cmilib: false

# Submitter GUI inventory name
# Can use CMILib color format if enable_cmilib is true
title: "&6&lSubmit your items"

# Disable/Enable default message when player succesfully submitted items.
enable_default_msg: false

# Specify default message when player succesfully submitted items
# You can use placeholder %player%, %point%, %point_name%
# Can use CMILib color format if enable_cmilib is true
default_msg: "&6Your island gained &a%point% &6%point_name% value."

# Specify the points name
# Example: point_name: "Point"
point_name: Point

# Specify if you want to hook Superior Skyblock Plugin
superior_skyblock_hook: false

# Specify if points are shared among
# Superior Skyblock island member
leaderboard_affect_ssb_island_member: false

# Specify if MMOItems is enabled in your server.
enable_mmoitems: false

# Specify the MMOItem Type with "TYPE:"
# Followed by the MMOItems ID and Value with "- MMOITEMSID:1000"
# Example: ARMOR:
#            - ARCANE_BOOTS:1000
mmoitems:
  ARMOR:
    - ARCANE_BOOTS:1000
    - ARCANE_HELM:1000
  SWORD:
    - CUTLASS:1000

# Specify the Minecraft item and Value with "MINECRAFT_ITEM: VALUE"
# Example: WHEAT: 20
minecraft_items:
  WHEAT: 20
  GOLDEN_CARROT: 50

# Specify the commands to run when player succesfully submitted items.
# You can use placeholder %player%, %point%, %point_name%
commands:
  - "is admin addbonus %player% worth %point%"

# Specify the leaderboard reset every what date of the month
leaderboard_reset_date: 1

# Specify the leaderboard reset every what time of the day
# Format is 24 hours.
# Example: "0030" (Using "" is a must)
leaderboard_reset_time: "0030"

# ===========================================================================================================================================#
