# Specify the points name
# Example: point_name: "NoName"
point_name: "NoName"

# Specify the MMOItem Type with "TYPE:"
# Followed by the MMOItems ID and Value with "- MMOITEMSID:1000"
# Example: ARMOR:
#            - ARCANE_BOOTS:1000
mmoitems:
  ARMOR:
    - ARCANE_BOOTS:1000
    - ARCANE_HELM:1000
  SWORD:
    - CUTLASS:1000

# Specify the Minecraft item and Value with "MINECRAFT_ITEM: VALUE"
# Example: WHEAT: 20
minecraft_items:
  WHEAT: 20
  GOLDEN_CARROT: 50