name: Submitter
version: '1.7.3'
main: me.merunko.holocraft.Submitter
api-version: '1.19'
authors: [Merunko]
description: Submitter to gain a type of score.

commands:
  submitter:
    description: Default.
    usage: "Usage: /submitter open <playername>"
    permission: submitter.open

  reload:
    description: Reload the plugin.
    usage: "Usage: /submitter reload"
    permission: submitter.reload

  open:
    description: Open submitter menu.
    usage: "Usage: /submitter open <playername>"
    permission: submitter.open

  mmoinspect:
    description: Check MMOItems properties on main hand.
    usage: "Usage: /submitter mmoinspect"
    permission: submitter.mmoinspect

  inspect:
    description: Check Minecraft item properties on main hand.
    usage: "Usage: /submitter inspect"
    permission: submitter.inspect

  updateleaderboard:
    description: Update the leaderboard.
    usage: "Usage: /submitter updatelboard"
    permission: submitter.updatelboard

  set.reward:
    description: Set the reward for top player.
    usage: "Usage: /submitter set reward top1(1-7)"
    permission: submitter.set.reward

  debug.get.reward:
    description: Debugging purpose to test reward.
    usage: "Usage: /submitter debug get reward top1(1-7)"
    permission: submitter.debug.get.reward

  calculate.topitem:
    description: Calculate top submitted items.
    usage: "Usage: /submitter calculate topitem"
    permission: submitter.calculate.topitems

permissions:
  submitter.reload:
    description: Allows player to reload the plugin.
    default: op

  submitter.open:
    description: Allows player to open the submitter menu.
    default: op

  submitter.mmoinspect:
    description: Allows player inspect MMOItems.
    default: op

  submitter.inspect:
    description: Allows player to inspect Minecraft item.
    default: op

  submitter.updatelboard:
    description: Allows player to update the leaderboard.
    default: op

  submitter.set.reward:
    description: Allows player to set items rewards for top player.
    default: op

  submitter.debug.get.reward:
    description: Allows player to debugging test reward.
    default: op

  submitter.calculate.topitems:
    description: Allows player to calculate top submitted items.
    default: op

files:
  logs.txt: logs.txt
  topItem.txt: topItem.txt


