name: Submitter
version: '1.3'
main: me.merunko.holocraft.Submitter
api-version: '1.20'
authors: [Merunko]
description: Submitter to gain a type of score.

commands:
  submitter:
    description: Default.
    usage: "Usage: /submitter open <playername>"
    permission: submitter.open

  reload:
    description: Reload the plugin.
    usage: "Usage: /submitter reload"
    permission: submitter.reload

  open:
    description: Open submitter menu.
    usage: "Usage: /submitter open <playername>"
    permission: submitter.open

  mmoinspect:
    description: Check MMOItems properties on main hand.
    usage: "Usage: /submitter mmoinspect"
    permission: submitter.mmoinspect

  valueinspect:
    description: Check Minecraft item properties on main hand.
    usage: "Usage: /submitter valueinspect"
    permission: submitter.valueinspect

permissions:
  submitter.reload:
    description: Allows player to reload the plugin.
    default: op

  submitter.open:
    description: Allows player to open the submitter menu.
    default: op

  submitter.mmoinspect:
    description: Allows player inspect MMOItems.
    default: op

  submitter.valueinspect:
    description: Allows player to inspect Minecraft item.
    default: op

files:
  logs.txt: logs.txt


